
--Create Procedure GetPerson_In_ConvCaseList
--	@Name NVarChar(50) 
--As
--Select c1.[ФИО Осуждённого], c1.[Номер Дела]
--From ConvCaseList c1
--Where c1.[ФИО Осуждённого] Like '%'+@Name+'%'
----------------------------------------------
--Create Procedure GetRecord_by_Name
--	@Name nvarchar(50)
--As
--Select *
--From RecordList r1
--Where r1.[ФИО следователя] like '%'+@Name+'%' 
--or r1.[ФИО осуждённого] like '%'+@Name+'%'
----------------------------------------------
--Create Procedure GetRecord_by_ID
--	@ID nvarchar(30)
--As
--Select *
--From RecordList r1
--Where r1.[Номер Дела] = @ID